/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_imgstreaming_ScreenCapture */

#ifndef _Included_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
#define _Included_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
 * Method:    grabScreen
 * Signature: (IIIII[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture_grabScreen__IIIII_3B
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
 * Method:    grabScreen
 * Signature: (IIIIIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture_grabScreen__IIIIIJI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
