/*
 * Copyright @ 2015 Atlassian Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_imgstreaming_ScreenCapture */

#ifndef _Included_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
#define _Included_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
 * Method:    grabScreen
 * Signature: (IIIII[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture_grabScreen__IIIII_3B
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     org_jitsi_impl_neomedia_imgstreaming_ScreenCapture
 * Method:    grabScreen
 * Signature: (IIIIIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_imgstreaming_ScreenCapture_grabScreen__IIIIIJI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
