/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager
#define _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager_init
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager
 * Method:    getCaptureDevices
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSManager_getCaptureDevices
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
