/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
#define _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    ARGB32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_ARGB32
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    AYUV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_AYUV
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    I420
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_I420
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IF09
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IF09
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IMC1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IMC1
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IMC2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IMC2
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IMC3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IMC3
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IMC4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IMC4
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    IYUV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_IYUV
(JNIEnv *, jclass);

/*
* Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
* Method:    MJPG
* Signature: ()I
*/
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_MJPG
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    NV12
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_NV12
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    RGB24
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_RGB24
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    RGB32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_RGB32
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    UYVY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_UYVY
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    Y211
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_Y211
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    Y411
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_Y411
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    Y41P
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_Y41P
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    YUY2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_YUY2
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    YV12
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_YV12
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    YVU9
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_YVU9
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat
 * Method:    YVYU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_directshow_DSFormat_YVYU
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
