/*
 * Copyright @ 2015 Atlassian Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_quicktime_QTCaptureDevice */

#ifndef _Included_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
#define _Included_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    formatDescriptions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_formatDescriptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    inputDevicesWithMediaType
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_inputDevicesWithMediaType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    isConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_isConnected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    localizedDisplayName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_localizedDisplayName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    open
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    uniqueID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jitsi_impl_neomedia_quicktime_QTCaptureDevice_uniqueID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
