/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_quicktime_NSObject */

#ifndef _Included_org_jitsi_impl_neomedia_quicktime_NSObject
#define _Included_org_jitsi_impl_neomedia_quicktime_NSObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_quicktime_NSObject
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_quicktime_NSObject_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_NSObject
 * Method:    retain
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_quicktime_NSObject_retain
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
