/*
 * Copyright @ 2015 Atlassian Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_quicktime_CVPixelBuffer */

#ifndef _Included_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
#define _Included_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getByteCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_getByteCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_getBytes__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getBytes
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_getBytes__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    memcpy
 * Signature: ([BIIJ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBuffer_memcpy
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
