/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_quicktime_NSDictionary */

#ifndef _Included_org_jitsi_impl_neomedia_quicktime_NSDictionary
#define _Included_org_jitsi_impl_neomedia_quicktime_NSDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_quicktime_NSDictionary
 * Method:    intForKey
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_quicktime_NSDictionary_intForKey
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
