/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey */

#ifndef _Included_org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey
#define _Included_org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferHeightKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferHeightKey
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferPixelFormatTypeKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferPixelFormatTypeKey
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferWidthKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferWidthKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
