/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_device_MacCoreAudioDevice */

#ifndef _Included_org_jitsi_impl_neomedia_device_MacCoreAudioDevice
#define _Included_org_jitsi_impl_neomedia_device_MacCoreAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jitsi_impl_neomedia_device_MacCoreAudioDevice_DEFAULT_SAMPLE_RATE
#define org_jitsi_impl_neomedia_device_MacCoreAudioDevice_DEFAULT_SAMPLE_RATE 44100.0
/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getDeviceUIDList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getDeviceUIDList
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    isInputDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_isInputDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    isOutputDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_isOutputDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getTransportTypeBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getTransportTypeBytes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getNominalSampleRate
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getNominalSampleRate
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getMinimalNominalSampleRate
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getMinimalNominalSampleRate
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getMaximalNominalSampleRate
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getMaximalNominalSampleRate
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getDefaultInputDeviceUIDBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getDefaultInputDeviceUIDBytes
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    getDefaultOutputDeviceUIDBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_getDefaultOutputDeviceUIDBytes
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    startStream
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_startStream
  (JNIEnv *, jclass, jstring, jobject,
        jfloat sampleRate,
        jint nbChannels,
        jint bitsPerChannel,
        jboolean isFloat,
        jboolean isBigEndian,
        jboolean isNonInterleaved,
        jboolean isInput,
        jboolean isEchoCancel);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    stopStream
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_stopStream
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    countInputChannels
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_countInputChannels
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_device_MacCoreAudioDevice
 * Method:    countOutputChannels
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_device_MacCoreAudioDevice_countOutputChannels
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
