/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest */

#ifndef _Included_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
#define _Included_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_DigestFinal_ex
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1DigestFinal_1ex
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_DigestInit_ex
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1DigestInit_1ex
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_DigestUpdate
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1DigestUpdate
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_MD_CTX_block_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1MD_1CTX_1block_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_MD_CTX_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1MD_1CTX_1create
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_MD_CTX_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1MD_1CTX_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_MD_CTX_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1MD_1CTX_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest
 * Method:    EVP_sha1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_transform_srtp_OpenSSLDigest_EVP_1sha1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
