/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice */

#ifndef _Included_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
#define _Included_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
 * Method:    getDeviceNameBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice_getDeviceNameBytes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
 * Method:    setInputDeviceVolume
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice_setInputDeviceVolume
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
 * Method:    setOutputDeviceVolume
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice_setOutputDeviceVolume
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
 * Method:    getInputDeviceVolume
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice_getInputDeviceVolume
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice
 * Method:    getOutputDeviceVolume
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jitsi_impl_neomedia_coreaudio_CoreAudioDevice_getOutputDeviceVolume
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
