/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
#define _Included_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    close
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_close
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    open
 * Signature: (Ljava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    paint
 * Signature: (JLjava/awt/Component;Ljava/awt/Graphics;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_paint
  (JNIEnv *, jclass, jlong, jobject, jobject, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    process
 * Signature: (JLjava/awt/Component;[IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_process
  (JNIEnv *, jclass, jlong, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    sysctlbyname
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_sysctlbyname
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
