/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_portaudio_Pa_HostApiTypeId */

#ifndef _Included_org_jitsi_impl_neomedia_portaudio_Pa_HostApiTypeId
#define _Included_org_jitsi_impl_neomedia_portaudio_Pa_HostApiTypeId
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
