/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder */

#ifndef _Included_org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder
#define _Included_org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder
 * Method:    g722_decoder_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder_g722_1decoder_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder
 * Method:    g722_decoder_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder_g722_1decoder_1open
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder
 * Method:    g722_decoder_process
 * Signature: (J[BI[BII)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_g722_JNIDecoder_g722_1decoder_1process
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
