/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
#define _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_MEDIA_TYPE_fill
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZZILjava/lang/String;JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1MEDIA_1TYPE_1fill
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jboolean, jint, jstring, jlong, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_MEDIA_TYPE_setCbFormat
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1MEDIA_1TYPE_1setCbFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_MEDIA_TYPE_setFormattype
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1MEDIA_1TYPE_1setFormattype
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_MEDIA_TYPE_setLSampleSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1MEDIA_1TYPE_1setLSampleSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_MEDIA_TYPE_setPbFormat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1MEDIA_1TYPE_1setPbFormat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_OUTPUT_DATA_BUFFER_alloc
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1OUTPUT_1DATA_1BUFFER_1alloc
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_OUTPUT_DATA_BUFFER_getDwStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1OUTPUT_1DATA_1BUFFER_1getDwStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    DMO_OUTPUT_DATA_BUFFER_setDwStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_DMO_1OUTPUT_1DATA_1BUFFER_1setDwStatus
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_AddRef
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1AddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_GetBuffer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1GetBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_GetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1GetLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_GetMaxLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1GetMaxLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_Release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1Release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaBuffer_SetLength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaBuffer_1SetLength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_Flush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1Flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_GetInputStatus
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1GetInputStatus
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_ProcessInput
 * Signature: (JIJIJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1ProcessInput
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_ProcessOutput
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1ProcessOutput
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_QueryInterface
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1QueryInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1Release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_SetInputType
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1SetInputType
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IMediaObject_SetOutputType
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IMediaObject_1SetOutputType
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IPropertyStore_SetValue
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IPropertyStore_1SetValue__JJZ
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    IPropertyStore_SetValue
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_IPropertyStore_1SetValue__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MediaBuffer_alloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MediaBuffer_1alloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MediaBuffer_pop
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MediaBuffer_1pop
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MediaBuffer_push
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MediaBuffer_1push
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MoCreateMediaType
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MoCreateMediaType
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MoDeleteMediaType
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MoDeleteMediaType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MoFreeMediaType
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MoFreeMediaType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP
 * Method:    MoInitMediaType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_wasapi_VoiceCaptureDSP_MoInitMediaType
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
