/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_codec_video_VPX */

#ifndef _Included_org_jitsi_impl_neomedia_codec_video_VPX
#define _Included_org_jitsi_impl_neomedia_codec_video_VPX
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jitsi_impl_neomedia_codec_video_VPX_CODEC_OK
#define org_jitsi_impl_neomedia_codec_video_VPX_CODEC_OK 0L
#undef org_jitsi_impl_neomedia_codec_video_VPX_CODEC_LIST_END
#define org_jitsi_impl_neomedia_codec_video_VPX_CODEC_LIST_END 9L
#undef org_jitsi_impl_neomedia_codec_video_VPX_CODEC_USE_XMA
#define org_jitsi_impl_neomedia_codec_video_VPX_CODEC_USE_XMA 1L
#undef org_jitsi_impl_neomedia_codec_video_VPX_CODEC_USE_OUTPUT_PARTITION
#define org_jitsi_impl_neomedia_codec_video_VPX_CODEC_USE_OUTPUT_PARTITION 131072L
#undef org_jitsi_impl_neomedia_codec_video_VPX_IMG_FMT_I420
#define org_jitsi_impl_neomedia_codec_video_VPX_IMG_FMT_I420 258L
#undef org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_VBR
#define org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_VBR 0L
#undef org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_CBR
#define org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_CBR 1L
#undef org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_CQ
#define org_jitsi_impl_neomedia_codec_video_VPX_RC_MODE_CQ 2L
#undef org_jitsi_impl_neomedia_codec_video_VPX_KF_MODE_AUTO
#define org_jitsi_impl_neomedia_codec_video_VPX_KF_MODE_AUTO 1L
#undef org_jitsi_impl_neomedia_codec_video_VPX_KF_MODE_DISABLED
#define org_jitsi_impl_neomedia_codec_video_VPX_KF_MODE_DISABLED 1L
#undef org_jitsi_impl_neomedia_codec_video_VPX_DL_REALTIME
#define org_jitsi_impl_neomedia_codec_video_VPX_DL_REALTIME 1L
#undef org_jitsi_impl_neomedia_codec_video_VPX_CODEC_CX_FRAME_PKT
#define org_jitsi_impl_neomedia_codec_video_VPX_CODEC_CX_FRAME_PKT 0L
#undef org_jitsi_impl_neomedia_codec_video_VPX_INTEFACE_VP8_DEC
#define org_jitsi_impl_neomedia_codec_video_VPX_INTEFACE_VP8_DEC 0L
#undef org_jitsi_impl_neomedia_codec_video_VPX_INTERFACE_VP8_ENC
#define org_jitsi_impl_neomedia_codec_video_VPX_INTERFACE_VP8_ENC 1L
/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_ctx_malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1ctx_1malloc
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_dec_init
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1dec_1init
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_decode
 * Signature: (J[BIIJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1decode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_get_frame
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1get_1frame
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_get_mem_map
 * Signature: (J[J[J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1get_1mem_1map
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_set_mem_map
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1set_1mem_1map
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_init
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1init
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_config_set
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1config_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_encode
 * Signature: (JJ[BIIIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1encode
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_get_cx_data
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1get_1cx_1data
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_cx_pkt_get_kind
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1cx_1pkt_1get_1kind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_cx_pkt_get_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1cx_1pkt_1get_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_cx_pkt_get_data
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1cx_1pkt_1get_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1malloc
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_w
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1w
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_h
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1h
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_d_w
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1d_1w
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_d_h
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1d_1h
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_plane0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1plane0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_plane1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1plane1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_plane2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1plane2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_stride0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1stride0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_stride1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1stride1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_stride2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1stride2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_get_fmt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1get_1fmt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_w
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1w
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_h
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1h
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_d_w
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1d_1w
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_d_h
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1d_1h
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_stride0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1stride0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_stride1
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1stride1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_stride2
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1stride2
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_stride3
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1stride3
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_fmt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1fmt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_set_bps
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1set_1bps
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    img_wrap
 * Signature: (JIIIIJ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_img_1wrap
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_dec_cfg_malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1dec_1cfg_1malloc
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_dec_cfg_set_w
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1dec_1cfg_1set_1w
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_dec_cfg_set_h
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1dec_1cfg_1set_1h
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1malloc
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_config_default
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1config_1default
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_profile
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1profile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_threads
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1threads
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_w
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1w
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_h
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1h
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_error_resilient
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1error_1resilient
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_target_bitrate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1target_1bitrate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_dropframe_thresh
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1dropframe_1thresh
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_resize_allowed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1resize_1allowed
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_resize_up_thresh
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1resize_1up_1thresh
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_resize_down_thresh
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1resize_1down_1thresh
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_end_usage
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1end_1usage
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_min_quantizer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1min_1quantizer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_max_quantizer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1max_1quantizer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_undershoot_pct
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1undershoot_1pct
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_overshoot_pct
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1overshoot_1pct
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_buf_sz
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1buf_1sz
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_buf_initial_sz
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1buf_1initial_1sz
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_rc_buf_optimal_sz
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1rc_1buf_1optimal_1sz
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_kf_mode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1kf_1mode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_kf_min_dist
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1kf_1min_1dist
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_enc_cfg_set_kf_max_dist
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1enc_1cfg_1set_1kf_1max_1dist
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    stream_info_malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_stream_1info_1malloc
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    stream_info_get_w
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_stream_1info_1get_1w
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    stream_info_get_h
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_stream_1info_1get_1h
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    stream_info_get_is_kf
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_stream_1info_1get_1is_1kf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_peek_stream_info
 * Signature: (I[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1peek_1stream_1info
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_mmap_get_sz
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1mmap_1get_1sz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_mmap_set_base
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1mmap_1set_1base
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_malloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    memcpy
 * Signature: ([BJI)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_memcpy
  (JNIEnv *, jclass, jbyteArray, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_VPX
 * Method:    codec_err_to_string
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_video_VPX_codec_1err_1to_1string
  (JNIEnv *, jclass, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
