/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_sctp4j_Sctp */

#ifndef _Included_org_jitsi_sctp4j_Sctp
#define _Included_org_jitsi_sctp4j_Sctp
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jitsi_sctp4j_Sctp_MSG_NOTIFICATION
#define org_jitsi_sctp4j_Sctp_MSG_NOTIFICATION 8192L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_CHANGE
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_CHANGE 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_PEER_ADDR_CHANGE
#define org_jitsi_sctp4j_Sctp_SCTP_PEER_ADDR_CHANGE 2L
#undef org_jitsi_sctp4j_Sctp_SCTP_REMOTE_ERROR
#define org_jitsi_sctp4j_Sctp_SCTP_REMOTE_ERROR 3L
#undef org_jitsi_sctp4j_Sctp_SCTP_SEND_FAILED
#define org_jitsi_sctp4j_Sctp_SCTP_SEND_FAILED 4L
#undef org_jitsi_sctp4j_Sctp_SCTP_SHUTDOWN_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_SHUTDOWN_EVENT 5L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADAPTATION_INDICATION
#define org_jitsi_sctp4j_Sctp_SCTP_ADAPTATION_INDICATION 6L
#undef org_jitsi_sctp4j_Sctp_SCTP_PARTIAL_DELIVERY_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_PARTIAL_DELIVERY_EVENT 7L
#undef org_jitsi_sctp4j_Sctp_SCTP_AUTHENTICATION_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_AUTHENTICATION_EVENT 8L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_EVENT 9L
#undef org_jitsi_sctp4j_Sctp_SCTP_SENDER_DRY_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_SENDER_DRY_EVENT 10L
#undef org_jitsi_sctp4j_Sctp_SCTP_NOTIFICATIONS_STOPPED_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_NOTIFICATIONS_STOPPED_EVENT 11L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_RESET_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_RESET_EVENT 12L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_CHANGE_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_CHANGE_EVENT 13L
#undef org_jitsi_sctp4j_Sctp_SCTP_SEND_FAILED_EVENT
#define org_jitsi_sctp4j_Sctp_SCTP_SEND_FAILED_EVENT 14L
#undef org_jitsi_sctp4j_Sctp_SCTP_COMM_UP
#define org_jitsi_sctp4j_Sctp_SCTP_COMM_UP 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_COMM_LOST
#define org_jitsi_sctp4j_Sctp_SCTP_COMM_LOST 2L
#undef org_jitsi_sctp4j_Sctp_SCTP_RESTART
#define org_jitsi_sctp4j_Sctp_SCTP_RESTART 3L
#undef org_jitsi_sctp4j_Sctp_SCTP_SHUTDOWN_COMP
#define org_jitsi_sctp4j_Sctp_SCTP_SHUTDOWN_COMP 4L
#undef org_jitsi_sctp4j_Sctp_SCTP_CANT_STR_ASSOC
#define org_jitsi_sctp4j_Sctp_SCTP_CANT_STR_ASSOC 5L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_PR
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_PR 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_AUTH
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_AUTH 2L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_ASCONF
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_ASCONF 3L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_MULTIBUF
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_MULTIBUF 4L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_RE_CONFIG
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_RE_CONFIG 5L
#undef org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_MAX
#define org_jitsi_sctp4j_Sctp_SCTP_ASSOC_SUPPORTS_MAX 5L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_AVAILABLE
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_AVAILABLE 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_UNREACHABLE
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_UNREACHABLE 2L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_REMOVED
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_REMOVED 3L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_ADDED
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_ADDED 4L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_MADE_PRIM
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_MADE_PRIM 5L
#undef org_jitsi_sctp4j_Sctp_SCTP_ADDR_CONFIRMED
#define org_jitsi_sctp4j_Sctp_SCTP_ADDR_CONFIRMED 6L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_INCOMING_SSN
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_INCOMING_SSN 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_OUTGOING_SSN
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_OUTGOING_SSN 2L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_DENIED
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_DENIED 4L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_FAILED
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_FAILED 8L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_CHANGED_DENIED
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_CHANGED_DENIED 16L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_INCOMING
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_INCOMING 1L
#undef org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_OUTGOING
#define org_jitsi_sctp4j_Sctp_SCTP_STREAM_RESET_OUTGOING 2L
/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usersctp_socket
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_sctp4j_Sctp_usersctp_1socket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_send
 * Signature: (J[BZII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1send
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jint, jint);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1listen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_accept
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1accept
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_connect
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1connect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    usrsctp_finish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_sctp4j_Sctp_usrsctp_1finish
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_sctp4j_Sctp
 * Method:    on_network_in
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_sctp4j_Sctp_on_1network_1in
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
